[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "ie_utils"
author = "Ignacio Martínez de Toda"
author-email = "Imartinezdetoda@student.ie.edu"
description-file = "README.md"
requires = [
"pandas",
#flask, instead of specifying it here, we are doing it in the requirements.txt
]
